version: 0.1
log:
  level: info
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
# 完全禁用追踪和OpenTelemetry
profiling:
  enabled: false
# 对于Registry 3.x版本，使用空的追踪配置
tracing:
  service_name: registry
  attributes:
    environment: development
  # 设置为空配置禁用追踪
  exporter: {}
  # 或者明确设置为none
  # exporter: none
