apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    part-of: lunchbox
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
