apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
    part-of: lunchbox
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: console
    port: 9001
    targetPort: 9001
    protocol: TCP
  type: ClusterIP
