apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    part-of: lunchbox
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
