apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    part-of: lunchbox
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  type: LoadBalancer
