apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lunchbox-dev

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patches.yaml
  - resource-patches.yaml

commonLabels:
  environment: development
  version: "dev"

commonAnnotations:
  environment: development
  deployment-timestamp: "2024"

images:
  - name: nginx
    newTag: latest
  - name: postgres
    newTag: 15-alpine
  - name: redis
    newTag: 7-alpine
  - name: rabbitmq
    newTag: 3.12-management-alpine
  - name: minio
    newTag: latest
  - name: php-fpm
    newTag: 8.2-fpm-alpine
  - name: pgbouncer
    newTag: 1.19-alpine

configMapGenerator:
  - name: environment-config
    behavior: merge
    literals:
      - APP_ENV=development
      - APP_DEBUG=true
      - LOG_LEVEL=debug

secretGenerator:
  - name: development-secrets
    behavior: merge
    literals:
      - DB_PASSWORD=dev_password_123
      - REDIS_PASSWORD=dev_redis_pass
      - RABBITMQ_PASSWORD=dev_rabbit_pass
      - MINIO_ROOT_PASSWORD=dev_minio_pass

vars:
  - name: APP_REPLICAS
    objref:
      kind: Deployment
      name: nginx
      apiVersion: apps/v1
    fieldref:
      fieldpath: spec.replicas

replicas:
  - name: nginx
    count: 1
  - name: php-fpm
    count: 1
  - name: pgbouncer
    count: 1
