apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lunchbox-prod

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patches.yaml
  - resource-patches.yaml

commonLabels:
  environment: production
  version: "1.0.0"

commonAnnotations:
  environment: production
  deployment-timestamp: "2024"
  managed-by: kustomize

images:
  - name: nginx
    newTag: 1.25-alpine
  - name: postgres
    newTag: 15-alpine
  - name: redis
    newTag: 7-alpine
  - name: rabbitmq
    newTag: 3.12-management-alpine
  - name: minio
    newTag: RELEASE.2023-10-25T06-33-25Z
  - name: php-fpm
    newTag: 8.4-fpm-alpine
  - name: pgbouncer
    newTag: 1.19-alpine

configMapGenerator:
  - name: environment-config
    behavior: merge
    literals:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=info

secretGenerator:
  - name: production-secrets
    behavior: merge
    envs:
      - secrets.env

vars:
  - name: APP_REPLICAS
    objref:
      kind: Deployment
      name: nginx
      apiVersion: apps/v1
    fieldref:
      fieldpath: spec.replicas

replicas:
  - name: nginx
    count: 3
  - name: php-fpm
    count: 3
  - name: pgbouncer
    count: 2
  - name: redis
    count: 2
  - name: minio
    count: 2

patches:
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: fast-ssd
  - target:
      kind: Service
      name: nginx
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /metadata/annotations
        value:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account:certificate/cert-id"
