apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lunchbox

resources:
  - nginx/deployment.yaml
  - nginx/service.yaml
  - nginx/configmap.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - postgres/configmap.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - rabbitmq/statefulset.yaml
  - rabbitmq/service.yaml
  - minio/deployment.yaml
  - minio/service.yaml
  - php-fpm/deployment.yaml
  - php-fpm/service.yaml
  - pgbouncer/deployment.yaml
  - pgbouncer/service.yaml

commonLabels:
  app: lunchbox
  part-of: lunchbox

commonAnnotations:
  version: "1.0.0"
  managed-by: kustomize
