name: Sync Base Images

on:
  workflow_dispatch:
    inputs:
      image_selection:
        description: "选择要同步的基础镜像"
        required: true
        type: choice
        options:
          - nginx
          - redis
          - postgres
          - mysql
          - node
          - python
          - golang
          - all
      tags:
        description: "要同步的tag列表（逗号分隔，如：alpine,latest,1.2.3）"
        required: false
        type: string
        default: ""

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Login to Tencent Cloud Registry
        run: |
          echo "${{ secrets.TENCENT_REGISTRY_PASSWORD }}" | skopeo login \
            --username "${{ secrets.TENCENT_REGISTRY_USERNAME }}" \
            --password-stdin \
            ccr.ccs.tencentyun.com

      - name: Sync images
        run: |
          # 定义镜像映射和默认tags
          declare -A IMAGE_MAP=(
            ["nginx"]="nginx"
            ["redis"]="redis"
            ["postgres"]="postgres"
            ["mysql"]="mysql"
            ["node"]="node"
            ["python"]="python"
            ["golang"]="golang"
          )

          declare -A DEFAULT_TAGS=(
            ["nginx"]="mainline-alpine,latest"
            ["redis"]="7.4-alpine,latest"
            ["postgres"]="17.6-alpine,latest"
            ["mysql"]="8.0,latest"
            ["node"]="22-alpine,latest"
            ["python"]="3.12-alpine,latest"
            ["golang"]="1.23-alpine,latest"
          )

          # 获取选中的镜像
          SELECTED_IMAGE="${{ github.event.inputs.image_selection }}"

          # 获取要同步的tag列表，如果为空则使用默认tags
          TAGS_INPUT="${{ github.event.inputs.tags }}"
          if [ -z "$TAGS_INPUT" ]; then
            echo "使用默认tags配置"
            if [ "$SELECTED_IMAGE" = "all" ]; then
              # 合并所有镜像的默认tags（去重）
              ALL_TAGS=""
              for image_name in "${!DEFAULT_TAGS[@]}"; do
                ALL_TAGS+="${DEFAULT_TAGS[$image_name]},"
              done
              IFS=',' read -ra TAG_LIST <<< $(echo "$ALL_TAGS" | tr ',' '\n' | sort -u | tr '\n' ',' | sed 's/,$//')
            else
              IFS=',' read -ra TAG_LIST <<< "${DEFAULT_TAGS[$SELECTED_IMAGE]}"
            fi
          else
            IFS=',' read -ra TAG_LIST <<< "$TAGS_INPUT"
          fi

          echo "将同步以下tags: ${TAG_LIST[*]}"

          # 确定要同步的镜像列表
          if [ "$SELECTED_IMAGE" = "all" ]; then
            # 同步所有镜像
            IMAGES=("${!IMAGE_MAP[@]}")
          else
            # 同步单个选中的镜像
            IMAGES=("$SELECTED_IMAGE")
          fi

          # 遍历所有选中的镜像
          for image_name in "${IMAGES[@]}"; do
            image_repo="${IMAGE_MAP[$image_name]}"

            # 遍历所有tag
            for tag in "${TAG_LIST[@]}"; do
              # 去除前后空格
              tag=$(echo "$tag" | xargs)

              # 源镜像地址（Docker Hub）
              source_image="docker.io/library/${image_repo}:${tag}"

              # 目标镜像地址（腾讯云个人仓库）
              target_image="ccr.ccs.tencentyun.com/${{ secrets.TENCENT_REGISTRY_NAMESPACE }}/${image_repo}:${tag}"

              echo "正在同步镜像: $source_image -> $target_image"

              # 使用 skopeo copy 同步镜像
              skopeo copy \
                --src-tls-verify=false \
                --dest-tls-verify=false \
                docker://$source_image \
                docker://$target_image

              if [ $? -eq 0 ]; then
                echo "✅ 镜像同步成功: ${image_repo}:${tag}"
              else
                echo "❌ 镜像同步失败: ${image_repo}:${tag}"
                exit 1
              fi
            done
          done
