apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    app: php-fpm
    part-of: lunchbox
spec:
  selector:
    app: php-fpm
  ports:
  - name: fpm
    port: 9000
    targetPort: 9000
    protocol: TCP
  type: ClusterIP
